CREATE TABLE discord_user(
   ID INTEGER NOT NULL AUTO_INCREMENT,
   userID VARCHAR(50) NOT NULL,
   CONSTRAINT PK_DISCORDUSER_ID PRIMARY KEY(ID)
);

CREATE TABLE hours(
   ID INTEGER NOT NULL AUTO_INCREMENT,
   userID INTEGER NOT NULL,
   hours DOUBLE NOT NULL,
   CONSTRAINT PK_HOURS_ID PRIMARY KEY(ID),
   CONSTRAINT FK_HOURS_TO_DISCORDUSER_userID FOREIGN KEY(userID) REFERENCES discord_user(ID)
);


SELECT *
FROM 
   hours JOIN discord_user 
   ON (hours.userID=discord_user.ID);